import os
import argparse
import json
import torch
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, Subset
from tqdm import tqdm
from scipy.stats import pearsonr
import matplotlib.pyplot as plt

from fusion_architectures import MultiModelFusion
from fusion_dataset import FusionDataset, collate_fusion

def compute_pearson(y_pred, y_true):
    """计算单个样本对的皮尔逊相关系数"""
    r, _ = pearsonr(y_pred, y_true)
    return r if not np.isnan(r) else 0.0

def parse_args():

    parser = argparse.ArgumentParser(description="Multi-Model Fusion 5-Fold Cross Validation Testing")
    parser = argparse.ArgumentParser(description="Multi-Model Fusion 5-Fold Cross Validation Testing")
    parser.add_argument('--data_dir', type=str, default="/data/ruiyan/lhj/TRIDENT/BRCA_LUAD_LUSC_STAD_LIHC_BLCA_BALANCED_WSI_FEATURES")
    parser.add_argument('--gene_csv', type=str, default="/data/ruiyan/lhj/gene_expression_label/combined_all_gene_expression_matrix.csv")
    parser.add_argument('--checkpoint_dir', type=str, default="/data/ruiyan/lhj/models_fusion/logs/alldata_fms_checkpoints",
                        help='Directory containing best_model_foldX.pth files')
    parser.add_argument('--split_file', type=str, default="/data/ruiyan/lhj/models_fusion/logs/alldata_fms_checkpoints/kfold_splits.json",
                        help='Path to kfold_splits.json generated by train_fusion.py')
    parser.add_argument('--output_dir', type=str, default="/data/ruiyan/lhj/models_fusion/logs/alldata_fms_test_results")


    parser.add_argument('--batch_size', type=int, default=32)
    parser.add_argument('--device', type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    return parser.parse_args()

def test_one_fold(model, loader, device):
    """在单折上进行测试，返回预测结果和指标"""
    model.eval()
    all_preds = []
    all_labels = []
    all_ids = []
    all_pearsons = []
    
    with torch.no_grad():
        for m_batches, labels, ids in tqdm(loader, desc="Testing", leave=False):
            m_batches = [m.to(device) for m in m_batches]
            outputs, _ = model(m_batches)
            
            preds_np = outputs.cpu().numpy()
            labels_np = labels.numpy()
            
            all_preds.append(preds_np)
            all_labels.append(labels_np)
            all_ids.extend(ids)
            
            for i in range(preds_np.shape[0]):
                r = compute_pearson(preds_np[i], labels_np[i])
                all_pearsons.append(r)
                
    all_preds = np.concatenate(all_preds, axis=0)
    all_labels = np.concatenate(all_labels, axis=0)
    
    return all_preds, all_labels, all_ids, all_pearsons

def main():
    args = parse_args()
    os.makedirs(args.output_dir, exist_ok=True)
    
    # input_dims = [768, 512, 512, 1280,768] # CHIEF, Feather, madeleine, prism,titan
    # model_names = ['CHIEF', 'Feather', 'madeleine', 'prism','titan']
    input_dims = [768, 512, 512, 1280,768, 768] # CHIEF, Feather, madeleine, prism,titan
    model_names = ['CHIEF', 'Feather', 'madeleine', 'prism','titan','GigaPath'] 
    
    print("="*60)
    print("Multi-Model Fusion 5-Fold Cross Validation Testing")
    print("="*60)
    
    # 1. 加载数据集
    print(f"\n[1] 加载数据集...")
    dataset = FusionDataset(args.data_dir, args.gene_csv, model_names=model_names)
    gene_names = dataset.gene_df.index.tolist()
    
    # 2. 加载折划分信息
    print(f"\n[2] 加载折划分信息: {args.split_file}")
    if not os.path.exists(args.split_file):
        print(f"错误: 找不到划分文件 {args.split_file}")
        print("请先运行 train_fusion.py 生成 kfold_splits.json")
        return
    
    with open(args.split_file, 'r') as f:
        split_info = json.load(f)
    
    n_folds = split_info['n_folds']
    print(f"   - 折数: {n_folds}")
    print(f"   - 随机种子: {split_info['seed']}")
    
    # 3. 逐折测试
    all_fold_results = []
    all_fold_pearsons = []
    all_predictions = []
    all_case_ids = []
    
    for fold_info in split_info['folds']:
        fold = fold_info['fold']
        test_idx = fold_info['test_idx']
        
        print(f"\n{'='*60}")
        print(f"Fold {fold} / {n_folds} 测试")
        print(f"{'='*60}")
        print(f"测试样本数: {len(test_idx)}")
        
        # 加载该折的模型
        checkpoint_path = os.path.join(args.checkpoint_dir, f"best_model_fold{fold}.pth")
        if not os.path.exists(checkpoint_path):
            print(f"警告: 找不到权重文件 {checkpoint_path}, 跳过该折")
            continue
            
        print(f"加载模型: {checkpoint_path}")
        model = MultiModelFusion(input_dims=input_dims, out_dim=dataset.gene_dim).to(args.device)
        model.load_state_dict(torch.load(checkpoint_path, map_location=args.device))
        
        # 创建该折的测试集 Loader
        test_sub = Subset(dataset, test_idx)
        loader = DataLoader(test_sub, batch_size=args.batch_size, shuffle=False, 
                            collate_fn=collate_fusion, num_workers=4)
        
        # 测试
        preds, labels, ids, pearsons = test_one_fold(model, loader, args.device)
        
        fold_mean_p = np.mean(pearsons)
        fold_std_p = np.std(pearsons)
        fold_mse = np.mean((preds - labels)**2)
        
        print(f"Fold {fold} 结果:")
        print(f"   - Mean Pearson R: {fold_mean_p:.4f} ± {fold_std_p:.4f}")
        print(f"   - MSE: {fold_mse:.4f}")
        
        all_fold_results.append({
            'fold': fold,
            'mean_pearson': fold_mean_p,
            'std_pearson': fold_std_p,
            'mse': fold_mse,
            'n_samples': len(test_idx)
        })
        
        all_fold_pearsons.extend(pearsons)
        all_predictions.append(preds)
        all_case_ids.extend(ids)
    
    # 4. 汇总结果
    print("\n" + "="*60)
    print("5-Fold Cross Validation 测试结果汇总")
    print("="*60)
    
    fold_means = [r['mean_pearson'] for r in all_fold_results]
    overall_mean = np.mean(fold_means)
    overall_std = np.std(fold_means)
    
    print(f"\n各折结果:")
    for r in all_fold_results:
        print(f"   Fold {r['fold']}: Pearson R = {r['mean_pearson']:.4f} ± {r['std_pearson']:.4f}, MSE = {r['mse']:.4f}")
    
    print(f"\n" + "-"*60)
    print(f"跨折平均 Pearson R: {overall_mean:.4f} ± {overall_std:.4f}")
    print(f"所有样本平均 Pearson R: {np.mean(all_fold_pearsons):.4f} ± {np.std(all_fold_pearsons):.4f}")
    print("="*60)
    
    # 5. 保存详细结果
    # 各样本的 Pearson 结果
    pearson_df = pd.DataFrame({
        'Case_ID': all_case_ids, 
        'Pearson_R': all_fold_pearsons
    })
    pearson_path = os.path.join(args.output_dir, "kfold_test_pearson.csv")
    pearson_df.to_csv(pearson_path, index=False)
    print(f"\n各样本 Pearson 结果: {pearson_path}")
    
    # 各折汇总结果
    summary_df = pd.DataFrame(all_fold_results)
    summary_path = os.path.join(args.output_dir, "kfold_test_summary.csv")
    summary_df.to_csv(summary_path, index=False)
    print(f"各折汇总结果: {summary_path}")
    
    # 6. 绘制分布图
    plt.figure(figsize=(12, 5))
    
    # 子图1: 各折箱线图
    plt.subplot(1, 2, 1)
    fold_data = []
    for fold_info in split_info['folds']:
        fold = fold_info['fold']
        n_samples = len(fold_info['test_idx'])
        start_idx = sum(len(fi['test_idx']) for fi in split_info['folds'][:fold-1])
        end_idx = start_idx + n_samples
        fold_data.append(all_fold_pearsons[start_idx:end_idx])
    
    plt.boxplot(fold_data, labels=[f'Fold {i+1}' for i in range(n_folds)])
    plt.ylabel('Pearson R')
    plt.title('Pearson R Distribution per Fold')
    plt.grid(axis='y', alpha=0.3)
    
    # 子图2: 整体直方图
    plt.subplot(1, 2, 2)
    plt.hist(all_fold_pearsons, bins=50, color='teal', edgecolor='black', alpha=0.7)
    plt.axvline(overall_mean, color='red', linestyle='--', label=f'Mean: {np.mean(all_fold_pearsons):.4f}')
    plt.xlabel('Pearson R')
    plt.ylabel('Frequency')
    plt.title('Overall Pearson R Distribution (All Folds)')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    
    plt.tight_layout()
    plot_path = os.path.join(args.output_dir, "kfold_test_distribution.png")
    plt.savefig(plot_path, dpi=150)
    print(f"分布图: {plot_path}")

if __name__ == "__main__":
    main()
